
[package]
name = "unicode-jp"
version = "0.1.0"
authors = ["gemmarx <gemmarx@users.noreply.github.com>"]

[lib]
name = "kana"
path = "src/kana.rs"

[[bin]]
name = "convert"
path = "src/main.rs"

[dependencies]
maplit = "*"
regex = "*"
clap = { version="*", features = ["yaml"] }

